config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end

  def search
    @posts = Post.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :text).merge(user_id: current_user.id, user_name: current_user.name)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @name = current_user.name
    @posts = current_user.posts
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShareSpace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    -# = javascript_pack_tag 'aplication', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    .header
      .left-header
        = link_to "/posts", class: "title" do
          ShareSpace
      .right-header
        - if user_signed_in?
          .register
            = link_to "/users/:id/edit", class: "user-btn" do
              = current_user.name
          .register
            = link_to "/users/#{current_user.id}", class: "user-btn" do
              マイページ
          .login
            = link_to "/posts/new", class: "login-btn" do
              投稿
        - else
          .register
            = link_to "/users/sign_up", class: "user-btn" do
              Sign up
          .login
            = link_to " /users/sign_in", class: "login-btn" do
              Login
    .top-image
      %p.top-text
        Welcome to ShareSpace
      .top-text-2
        エンジニアリングに関する知識を投稿してアウトプットしよう
    = yield
    .footer
      .footer-text
        ShareSpace

app/views/posts/_footer.html.haml
-# .footer
-#   .footer-text
-#     ShareSpace

app/views/posts/_header.html.haml
-# .header
-#   .left-header
-#     .title
-#     ShareS pace
-#   .right-header
-#     .register
-#       = link_to "#", class: "user-btn" do
-#         ユーザー登録
-#     .login
-#       = link_to "#", class: "login-btn" do
-#         ログイン
-# .top-image
-#   .top-text
-#     Welcome to ShareSpace
-#   .top-text-2
-#     エンジニアリングに関する知識を投稿してアウトプットしよう

app/views/posts/_main.html.haml
= render partial: 'posts/post', locals: { post: @post }

app/views/posts/_post.html.haml
.form
  .seach-form
    = form_with url: search_posts_path, local: true, method: :get do |form|
      = form.text_field :keyword, class: 'seach-text', placeholder: 'type a text'
      = form.submit 'seach', class: "seach-btn"
.content-main
  .content-box
    - @posts.each do |post|
      .content-post
        .content-title-icon
          = link_to post_path(post.id), method: :get, class: "post-text" do
            = post.title
          .icon-btn
            %ul.icon-text
              %li
                = link_to post_path(post.id), method: :get, class: "icon-text-2" do
                  詳細
                - if user_signed_in? && current_user.id == post.user_id
                  %li
                    = link_to edit_post_path(post.id), method: :get, class: "icon-text-2" do
                      編集
                      %li
                        = link_to post_path(post.id), method: :delete, class: "icon-text-2" do
                          削除
        .name-date-box
          .post-name
            = post.user_name
          .post-date
            = post.created_at.strftime("%Y年%m月%d日 %H時%M分")

app/views/posts/create.html.haml
.content-end
  .success
    投稿が完了しました。
  .success-end
    = link_to "/posts", class: "success-btn" do
      投稿一覧へ戻る

app/views/posts/destroy.html.haml
.content-end
  .success
    削除が完了しました
  .success-end
    = link_to "/posts", class: "success-btn" do
      投稿一覧へ戻る

app/views/posts/edit.html.haml
.new-contents-2
  .new-container-2
    .new-edit
      .edit
        編集
    = form_with model: @post, local: true, class: "new-all-2" do |form|
      = form.text_field :title, placeholder: "タイトル", class: "new-title-2"
      = form.text_area :text, placeholder: "プログラミングに関する知識を書いてアウトプットしよう", class: "new-text-2"
      .new-btn-box-2
        = form.submit "ShareSpaceに投稿", class: "new-btn-2"

app/views/posts/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "footer"

app/views/posts/new.html.haml
.new-contents
  .new-container
    = form_with model: @post, local: true, class: "new-all" do |form|
      = form.text_field :title, placeholder: "タイトル", class: "new-title", maxlength: "10"
      = form.text_area :text, placeholder: "プログラミングに関する知識を書いてアウトプットしよう", class: "new-text"
      .new-btn-box
        = form.submit "ShareSpaceに投稿", class: "new-btn"

app/views/posts/search.html.haml
= render partial: 'posts/post', locals: { post: @post }

app/views/posts/show.html.haml
.content-main-2
  .content-box-2
    .content-post-2
      .content-title-icon-2
        .post-text-2
          = @post.title
        .name-date-box-2
          .post-name-2
            = @post.user_name
          .post-date-2
            = @post.created_at.strftime("%Y年%m月%d日 %H時%M分")
            .icon-btn-2
              %ul.icon-text-2
                - if user_signed_in? && current_user.id == @post.user_id
                  %li
                    = link_to edit_post_path(@post.id), method: :get, class: "icon-text-2-2" do
                      編集
                      %li
                        = link_to post_path(@post.id), method: :delete, class: "icon-text-2-2" do
                          削除
            
    .show-text-box
      .show-text
        = @post.text
  .content-main
    .content-box
      .container
        - if current_user
          = form_with(model: [@post, @comment], local: true, id: "new-comment") do |form|
            .comment-text-btn
              = form.text_area :text, placeholder: "コメントする", rows: "2", class: "comment-text"
              = form.submit "SEND", class: "comment-btn"
        - else
          %p
            ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
      .comments 
        %h1
          <コメント一覧>
          - if @comments
            - @comments.each do |comment|
              .comment-name-text-2
                %p
                  .comment-name
                    = comment.user.name
                %p
                  ：
                %p
                  = comment.text

app/views/posts/update.html.haml
.content-end
  .success
    編集が完了しました
  .success-end
    = link_to "/posts", class: "success-btn" do
      投稿一覧へ戻る

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.haml
.content-main
  .post-list-name
    = current_user.name
    さんの投稿一覧
  .content-box
    - @posts.each do |post|
      .content-post
        .content-title-icon
          = link_to post_path(post.id), method: :get, class: "post-text" do
            = post.title
          .icon-btn
            %ul.icon-text
              %li
                = link_to post_path(post.id), method: :get, class: "icon-text-2" do
                  詳細
                - if user_signed_in? && current_user.id == post.user_id
                  %li
                    = link_to edit_post_path(post.id), method: :get, class: "icon-text-2" do
                      編集
                      %li
                        = link_to post_path(post.id), method: :delete, class: "icon-text-2" do
                          削除
        .name-date-box
          .post-name
            = post.user_name
          .post-date
            = post.created_at.strftime("%Y年%m月%d日 %H時%M分")